[build]
builder = "nixpacks"
buildCommand = "pnpm run build --filter=web"

[deploy]
startCommand = "pnpm --filter=web start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"